name: Test Repo A (Dispatcher)

on:
  workflow_dispatch:

jobs:
  dispatch:
    name: Dispatch
    env:
      PACKAGES_TO_UPGRADE: ${{ needs.run_publish.outputs.packages }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: ['LucasSantosDev/repo-B']
    timeout-minutes: 5
    steps:
      - run: |
          echo "${{ secrets.dev.USERNAME }}"
      - name: Dispatch to workflows
        run: |
            curl -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Authorization: token ${{ secrets.TOKEN_OTHER_REPO }}" \
            --request POST \
            --data '{"event_type": "Triggered by API", "client_payload": { "foo": "bar" }}' https://api.github.com/repos/${{ matrix.repo }}/dispatches
